export enum ActionType {
  OPEN_FORM = 'OPEN_FORM',
  CLOSE_FORM = 'CLOSE_FORM',
  ADD_INVOICE = 'ADD_INVOICE',
  GET_INVOICES = 'GET_INVOICES',
  SORT_INVOICES = 'SORT_INVOICES',
  SET_FILTER = 'SET_FILTER',
  START_LOADING = 'START_LOADING',
  SET_CURRENT_INVOICE = 'SET_CURRENT_INVOICE',
  UPDATE_INVOICE = 'UPDATE_INVOICE',
  START_EDITING = 'START_EDITING',
}
